name: Jest test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - uses: cschleiden/replace-tokens@v1
        env:
          TMBD_API: ${{ secrets.TMBD_API }}
          TMBD_API_KEY: ${{ secrets.TMBD_API_KEY }}
      - name: Run jest tests
        run: yarn test:jest
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: jest-result
          path: output/
          retention-days: 7
