name: Jest test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - uses: ./.github/actions/set-env-vars
        with:
          TMDB_API: ${{ secrets.TMDB_API }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          JWT_KEY: ${{ secrets.JWT_KEY  }}
      - name: Run jest tests
        run: yarn test:jest
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: jest-result
          path: output/
          retention-days: 7
